/**
 *	PieceMaker API client (JavaScript version) for Motion Bank.
 *
 *	See: 
 *	  http://piecemaker.org
 *	  http://motionbank.org
 *	  https://github.com/fjenett/piecemaker-api-client
 *
 *	Version: 0.0.1, build: 430
 */
 var PieceMakerApi=function(){var g=void 0,i=void 0,e=void 0,f=function(){},p=function(){};p.prototype={get:function(){},post:function(){},put:function(){},del:function(){},fetch:function(){}};var m=function(a){if(e&&"piecemakerError"in e&&"function"==typeof e.piecemakerError)e.piecemakerError(a);else throw a;},k=function(){};k.prototype=new p;k.prototype.get=function(a,b){this.fetch(a,b.url,"get",null,b.success,b.error||m)};k.prototype.put=function(a,b){this.fetch(a,b.url,"put",b.data,b.success,b.error||
m)};k.prototype.post=function(a,b){this.fetch(a,b.url,"post",b.data,b.success,b.error||m)};k.prototype.del=function(a,b){this.fetch(a,b.url,"delete",null,b.success,b.error||m)};k.prototype.fetch=function(a,b,c,h,e,d){i&&(h&&!("api_key"in h)?h.api_key=i:h||(h={api_key:i}));var f=(new Date).getTime();jQuery.ajax({url:b,type:c,dataType:"json",data:h,context:a,success:function(){arguments&&(arguments[0]&&"object"===typeof arguments[0]&&!("queryTime"in arguments[0]))&&(arguments[0].queryTime=(new Date).getTime()-
f);e.apply(a,arguments)},error:d,xhrFields:{withCredentials:!0}})};var j=function(a,b){this.targetWindow=a;this.targetOrigin=b;this.requests={}};j.prototype=new p;j.prototype.get=function(a,b){this.fetch(a,b.url,"get",null,b.success,b.error||m)};j.prototype.fetch=function(a,b,c,h,e,d){i&&(h&&!("api_key"in h)?h.api_key=i:h||(h={api_key:i}));b={url:b,type:c,dataType:"json",data:h,xhrFields:{withCredentials:!0}};for(c="piecemaker_request_"+(new Date).getTime();connector.requests[c];)c="piecemaker_request_"+
(new Date).getTime();connector.requests[c]={context:a,success:function(){e.apply(a,arguments)},error:function(a){d.call(null,a)}};connector.targetWindow.postMessage({name:"piecemakerapi",data:JSON.stringify({options:b,requestId:c})},connector.targetOrigin)};j.prototype.handle=function(a){connector.requests[a.requestId]?(connector.requests[a.requestId].success(a.data),delete connector.requests[a.requestId]):(console.log("Unable to find request with ID: "+a.requestId),console.log(a),console.log(connector.requests))};
var l=function(a){a&&("happened_at_float"in a&&"number"===typeof a.happened_at_float)&&(a.happened_at=new Date(a.happened_at_float),a.finished_at=new Date(a.happened_at.getTime()+1E3*a.duration))},o=function(a){if(a&&0!=a.length)for(var b=0,c=a.length;b<c;b++)n(a[b])},n=function(a){a&&("happened_at_float"in a&&"number"===typeof a.happened_at_float&&(a.happened_at=new Date(a.happened_at_float),a.finished_at=new Date(a.happened_at.getTime()+1E3*a.duration)),a.getHappenedAt=function(){return a.happened_at},
a.setHappenedAt=function(b){if(b instanceof"Date"){a.happened_at=b;a.happened_at_float=b.getTime()}},a.getEventType=function(){return a.event_type})},d=function(){var a=arguments[0];1==arguments.length&&"object"==typeof a?(e=a.context||{},i=a.api_key||!1,g=a.baseUrl||"http://localhost:3000"):(1<=arguments.length&&"object"==typeof arguments[0]&&(e=arguments[0]),2<=arguments.length&&"string"==typeof arguments[1]&&(i=arguments[1]),3<=arguments.length&&"string"==typeof arguments[2]&&(g=arguments[2]));
if(!i)throw"PieceMakerAPI: need an API_KEY for this to work";connector=new k};d.PIECE=1;d.PIECES=2;d.EVENT=3;d.EVENTS=4;d.VIDEO=5;d.VIDEOS=6;d.prototype.loadPiece=function(a,b){var c=b||f;connector.get(this,{url:g+"/api/piece/"+a,success:function(a){a.requestType=d.PIECE;c.call(e||b,a.piece)}})};d.prototype.loadPieces=function(a){var b=a||f;connector.get(this,{url:g+"/api/pieces",success:function(c){c.requestType=d.PIECES;b.call(e||a,c)}})};d.prototype.loadEventsForPiece=function(a,b){var c=b||f;
connector.get(this,{url:g+"/api/piece/"+a+"/events",success:function(a){a.requestType=d.EVENTS;o(a.events);c.call(e||b,a)}})};d.prototype.loadVideosForPiece=function(a,b){var c=b||f;connector.get(this,{url:g+"/api/piece/"+a+"/videos",success:function(a){a.requestType=d.VIDEOS;var f=a.videos;if(f&&0!=f.length)for(var g=0,i=f.length;g<i;g++)l(f[g]);c.call(e||b,a)}})};d.prototype.loadVideo=function(a,b){var c=b||f;connector.get(this,{url:g+"/api/video/"+a,success:function(a){a.requestType=d.VIDEO;a=
a.video;l(a);c.call(e||b,a)}})};d.prototype.createVideo=function(a,b){var c=b||f;connector.post(this,{url:g+"/api/video",data:a,success:function(a){a.requestType=d.VIDEO;a=a.video;l(a);c.call(e||b,a)}})};d.prototype.updateVideo=function(a,b,c){var h=c||f;"object"===typeof a&&"id"in a&&(a=a.id);connector.post(this,{url:g+"/api/video/"+a+"/update",data:b,success:function(a){a.requestType=d.VIDEO;a=a.video;l(a);h.call(e||c,a)}})};d.prototype.deleteVideo=function(a,b){var c=b||f;"object"===typeof a&&
"id"in a&&(a=a.id);connector.post(this,{url:g+"/api/video/"+a+"/delete",success:function(a){a.requestType=d.VIDEO;a=a.video;l(a);c.call(e||b,a)}})};d.prototype.loadEventsForVideo=function(a,b){var c=b||f;connector.get(this,{url:g+"/api/video/"+a+"/events",success:function(a){a.requestType=d.EVENTS;o(a.events);c.call(e||b,a)}})};d.prototype.loadEventsByTypeForVideo=function(a,b,c){var h=c||f;connector.get(this,{url:g+"/api/video/"+a+"/events/type/"+b,success:function(a){a.requestType=d.EVENTS;o(a.events);
h.call(e||c,a)}})};d.prototype.loadEventsBetween=function(a,b,c){var h=c||f;connector.get(this,{url:g+"/api/events/between/"+parseInt(a.getTime()/1E3)+"/"+parseInt(Math.ceil(b.getTime()/1E3)),success:function(a){a.requestType=d.EVENTS;o(a.events);h.call(e||c,a)}})};d.prototype.loadEvent=function(a,b){var c=b||f;connector.get(this,{url:g+"/api/event/"+a,success:function(a){a.requestType=d.EVENT;a=a.event;n(a);c.call(e||b,a)}})};d.prototype.createEvent=function(a,b){var c=b||f;connector.post(this,{url:g+
"/api/event",data:a,success:function(a){a.requestType=d.EVENT;a=a.event;n(a);c.call(e||b,a)}})};d.prototype.updateEvent=function(a,b,c){var h=c||f;connector.post(this,{url:g+"/api/event/"+a+"/update",data:b,success:function(a){a.requestType=d.EVENT;a=a.event;n(a);h.call(e||c,a)}})};d.prototype.deleteEvent=function(a,b){var c=b||f;"object"===typeof a&&"id"in a&&(a=a.id);connector.post(this,{url:g+"/api/event/"+a+"/delete",success:function(a){a.requestType=d.EVENT;a=a.event;n(a);c.call(e||b,a)}})};
d.prototype.findEvents=function(a,b){var c=b||f;connector.post(this,{url:g+"/api/events/find",data:a,success:function(a){a.requestType=d.EVENTS;o(a.events);c.call(e||b,a)}})};d.prototype.createCallback=function(){if(1==arguments.length)return e[arguments[0]];if(2<=arguments.length){var a=1,b=e,c=arguments[0];if("string"!==typeof arguments[0]){b=arguments[0];if("string"!==typeof arguments[1])throw"createCallback(): if first argument is a target then the second needs to be a method name";c=arguments[1];
a=2}if(arguments.length>a){for(var d=[];a<arguments.length;a++)d.push(arguments[a]);var f=b,g=c;return function(a){d.unshift(a);f[g].apply(f,d)}}return b[c]}throw"PieceMakerAPI error: wrong number of arguments";};d.prototype.useProxy=function(a,b){connector=new j(a,b);window.addEventListener("message",function(a){connector instanceof j&&(a.origin===connector.targetOrigin&&"piecemakerapi"===a.data.name)&&(a=JSON.parse(a.data),connector.handle(a.data))},!0)};d.prototype.fetch=function(a,b,c){connector.fetch(null,
a.url,a.type,a.data,b,c||m)};return d}(),EventTimeClusters=function(){var g=function(){this._from=this._to=null;this.events=[];this.videos=[];this.allEvents=[]};g.prototype.from=function(){return this._from};g.prototype.to=function(){return this._to};g.prototype.overlapsWith=function(e){return!this._from||!this._to?!1:!(e.happened_at.getTime()>this._to||e.finished_at.getTime()<this._from)};g.prototype.add=function(e){-1==this.allEvents.indexOf(e)&&this.allEvents.push(e);var f=e.happened_at;if(!this._from||
f.getTime()<this._from.getTime())this._from=new Date(f.getTime());f=e.finished_at;if(!this._to||f.getTime()>this._to.getTime())this._to=new Date(f.getTime());"event_type"in e?-1==this.events.indexOf(e)&&this.events.push(e):-1==this.videos.indexOf(e)&&this.videos.push(e)};g.prototype.addAll=function(e){for(var f=0,g=e.length;f<g;f++)this.add(e[f])};g.prototype.getAll=function(){return this.allEvents};g.prototype.getVideos=function(){return this.videos};g.prototype.getEvents=function(){return this.events};
g.prototype.toString=function(){return"EventTimeCluster: "+this._from+" "+this._to};var i=function(){};i.clusterEvents=function(e){for(var f=[],i=0,m=e.length;i<m;i++){for(var k=e[i],j=!1,l=0,o=f.length;l<o;l++){var n=f[l];if(n.overlapsWith(k)){n.add(k);j=!0;break}}j||(j=new g,f.push(j),j.add(k))}return f};return i}();if(!("$"in this))var $={ajax:function(){}};